language: node_js
node_js:
  - '6.7.0'
before_script:
  - npm install
  - npm install -g bower
  - bower install
  - npm run gulp    
script:
  - git config --global user.email "${GITHUB_MAIL}"
  - git config --global user.name "${GITHUB_USER}"
  - git add .
  - MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
  - git commit -m "Site updated:$MESSAGE"
  - git push "https://${GITHUB_TOKEN}@github.com/weihanchen/puzzle-game-threes1536.git" master:gh-pages
branches:
  only:
    - master
notification:
  email:
    - ${GITHUB_MAIL}
  on_success: always