language: node_js
node_js:
  - '6.7.0'
before_script:
  - npm install
  - npm install -g bower
  - bower install
script:
  - bash scripts/deploy.sh
branches:
  only:
    - master
notification:
  email:
    - ${GITHUB_MAIL}
  on_success: always