language: node_js
node_js:
  - '6.7.0'
before_script:
  - npm install -g bower
  - bower install
script:
  # build
  - npm run gulp 
deploy:
  # keep the build we just made with "npm test" (dist/)
  provider: script
  skip_cleanup: true
  script:
    - git config --global user.email "${GITHUB_MAIL}"
    - git config --global user.name "${GITHUB_USER}"
    - git add .
    - MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
    - git commit -m "Site updated:${MESSAGE}"
    - git push --force "https://${GITHUB_TOKEN}@github.com/weihanchen/puzzle-game-threes1536.git" $SOURCE_BRANCH:$TARGET_BRANCH > /dev/null 2>&1

branches:
  only:
    - master

notification:
  email:
    - ${GITHUB_MAIL}
  on_success: always